[RELAY/FEE_API] [FEAT] Include triggered transfer txs from relay to transfer fee
ambrosus/ambrosus-bridge pull request #303
Opened 2022-07-25 09:16 UTC by nacknime-official

Closes #297

2022-08-04 12:56 UTC, SvineruS requested changes

2022-08-04 12:56 UTC, SvineruS commented on relay/internal/service_fee/fee_helper/transfer_fee.go
> +		errGroup.Go(getAndSaveTotalGasParams(sideClient, txHash))
totalGasCost must be in same currency

2022-08-11 17:15 UTC, nacknime-official commented on relay/internal/service_fee/fee_helper/transfer_fee.go
> +		errGroup.Go(getAndSaveTotalGasParams(sideClient, txHash))
Done

2022-08-31 22:11 UTC, SvineruS commented
closed in favor of #317

2022-08-31 22:11 UTC, closed without merging